insert into rol (nombre) values ('ADMIN');
insert into rol (nombre) values ('USER');
insert into rol (nombre) values ('INVITED');
insert into rol (nombre) values ('DEVELOPER');
insert into permiso (nombre) values ('READ');
insert into permiso (nombre) values ('REFACTOR');
insert into permiso (nombre) values ('UPDATE');
insert into permiso (nombre) values ('CREATE');
insert into permiso (nombre) values ('REFACTOR');
insert into permiso (nombre) values ('WRITE');
insert into usuario (username, password, isEnabled, accountNoexpired, accountNoLocked, credentialNoExpired) values ('npoznan0', 'lB6&J5Pt>S', false, true, true, true);
insert into usuario (username, password, isEnabled, accountNoexpired, accountNoLocked, credentialNoExpired) values ('jcran1', 'uG4,T"hka)z|', true, true, true, false);
insert into usuario (username, password, isEnabled, accountNoexpired, accountNoLocked, credentialNoExpired) values ('lpinar2', 'rM4.ff2''dex#l', false, false, true, false);
insert into usuario (username, password, isEnabled, accountNoexpired, accountNoLocked, credentialNoExpired) values ('llindholm3', 'oB4<b){u', true, true, false, true);
insert into usuario (username, password, isEnabled, accountNoexpired, accountNoLocked, credentialNoExpired) values ('mbaudinot4', 'xE9}8rvY''_hix', true, false, false, false);
insert into usuario (username, password, isEnabled, accountNoexpired, accountNoLocked, credentialNoExpired) values ('celsy5', 'hK7,ORG@,Cfi_6O<', false, true, true, true);
insert into usuario (username, password, isEnabled, accountNoexpired, accountNoLocked, credentialNoExpired) values ('ipersent6', 'eO5#<xL&%?ns@H', true, true, false, false);
insert into usuario (username, password, isEnabled, accountNoexpired, accountNoLocked, credentialNoExpired) values ('cwoolham7', 'iX3\@|xN/5', false, true, true, false);
insert into usuario (username, password, isEnabled, accountNoexpired, accountNoLocked, credentialNoExpired) values ('awellstood8', 'rU9$df?)Y', false, true, true, false);
insert into usuario (username, password, isEnabled, accountNoexpired, accountNoLocked, credentialNoExpired) values ('lskeleton9', 'vF9)>K=jpaj5zMjT', false, true, true, true);
insert into usuario (username, password, isEnabled, accountNoexpired, accountNoLocked, credentialNoExpired) values ('ivalentettia', 'mT6`#AO3E2bN\v', true, true, false, true);
insert into usuario (username, password, isEnabled, accountNoexpired, accountNoLocked, credentialNoExpired) values ('gmurdieb', 'wM3.xv)?If', false, false, true, false);
insert into usuario (username, password, isEnabled, accountNoexpired, accountNoLocked, credentialNoExpired) values ('cbaynomc', 'qY2"%}7MR', true, false, true, false);
insert into usuario (username, password, isEnabled, accountNoexpired, accountNoLocked, credentialNoExpired) values ('bjohanssond', 'lF5''MavD\', true, true, false, false);
insert into usuario (username, password, isEnabled, accountNoexpired, accountNoLocked, credentialNoExpired) values ('nfilipponee', 'uI6?D*W$/Ph', true, true, true, false);
insert into tarea (titulo, descripcion, expira, completado, id_usuario) values ('Preparar el almuerzo para llevar', 'Liquidar los pagos pendientes de servicios o productos', '12/6/2023', false, '1');
insert into tarea (titulo, descripcion, expira, completado, id_usuario) values ('Hacer ejercicio', 'como en el trabajo o la escuela', '10/11/2023', true, '2');
insert into tarea (titulo, descripcion, expira, completado, id_usuario) values ('Escribir en el diario', 'como en el trabajo o la escuela', '8/1/2023', true, '3');
insert into tarea (titulo, descripcion, expira, completado, id_usuario) values ('Planificar la semana', 'Anotar las actividades que se deben realizar al día siguiente para organizarse mejor', '6/2/2023', false, '4');
insert into tarea (titulo, descripcion, expira, completado, id_usuario) values ('Meditar durante 10 minutos', 'Realizar una caminata corta o larga para ejercitarse y disfrutar del aire libre', '1/19/2024', false, '5');
insert into tarea (titulo, descripcion, expira, completado, id_usuario) values ('Hacer una llamada de seguimiento a un cliente', 'Coordinar un encuentro con compañeros de trabajo para discutir proyectos o asuntos importantes', '11/29/2023', true, '6');
insert into tarea (titulo, descripcion, expira, completado, id_usuario) values ('Organizar el armario', 'Contactar al consultorio médico para programar una cita', '5/10/2023', true, '7');
insert into tarea (titulo, descripcion, expira, completado, id_usuario) values ('Comprar comestibles', 'Buscar información en línea o en libros sobre un tema que resulte interesante', '9/17/2023', true, '8');
insert into tarea (titulo, descripcion, expira, completado, id_usuario) values ('Revisar y responder correos electrónicos', 'Preparar comida para consumir fuera de casa', '1/21/2024', false, '9');
insert into tarea (titulo, descripcion, expira, completado, id_usuario) values ('Estudiar para un examen', 'experiencias o reflexiones en un diario personal', '5/10/2023', false, '10');
insert into tarea (titulo, descripcion, expira, completado, id_usuario) values ('Hacer ejercicio', 'Practicar la meditación durante un corto período de tiempo para relajarse y mejorar la concentración', '12/16/2023', false, '11');
insert into tarea (titulo, descripcion, expira, completado, id_usuario) values ('Programar una reunión con colegas', 'Verificar la bandeja de entrada del correo electrónico y responder los mensajes importantes', '5/31/2023', false, '12');
insert into tarea (titulo, descripcion, expira, completado, id_usuario) values ('Organizar el armario', 'Anotar las actividades que se deben realizar al día siguiente para organizarse mejor', '9/1/2023', true, '13');
insert into tarea (titulo, descripcion, expira, completado, id_usuario) values ('Escribir en el diario', 'como en el trabajo o la escuela', '1/4/2024', false, '14');
insert into tarea (titulo, descripcion, expira, completado, id_usuario) values ('Estudiar para un examen', 'Realizar una caminata corta o larga para ejercitarse y disfrutar del aire libre', '4/13/2024', false, '15');
insert into tarea (titulo, descripcion, expira, completado, id_usuario) values ('Preparar el almuerzo para llevar', 'Ordenar la ropa y los objetos almacenados en el armario', '5/26/2023', true, '1');
insert into tarea (titulo, descripcion, expira, completado, id_usuario) values ('Planificar la semana', 'Revisar material de estudio y repasar conceptos importantes para un examen próximo', '8/8/2023', false, '2');
insert into tarea (titulo, descripcion, expira, completado, id_usuario) values ('Comprar comestibles', 'Contactar al consultorio médico para programar una cita', '12/13/2023', true, '3');
insert into tarea (titulo, descripcion, expira, completado, id_usuario) values ('Investigar sobre un tema de interés', 'experiencias o reflexiones en un diario personal', '5/15/2023', true, '4');
insert into tarea (titulo, descripcion, expira, completado, id_usuario) values ('Hacer una llamada de seguimiento a un cliente', 'Practicar la meditación durante un corto período de tiempo para relajarse y mejorar la concentración', '9/26/2023', true, '5');
insert into rol_permiso (id_permiso, id_rol) values ('1', '1');
insert into rol_permiso (id_permiso, id_rol) values ('1', '2');
insert into rol_permiso (id_permiso, id_rol) values ('1', '3');
insert into rol_permiso (id_permiso, id_rol) values ('1', '4');
insert into rol_permiso (id_permiso, id_rol) values ('2', '1');
insert into rol_permiso (id_permiso, id_rol) values ('2', '2');
insert into rol_permiso (id_permiso, id_rol) values ('2', '3');
insert into rol_permiso (id_permiso, id_rol) values ('2', '4');
insert into rol_permiso (id_permiso, id_rol) values ('3', '1');
insert into rol_permiso (id_permiso, id_rol) values ('3', '2');
insert into rol_permiso (id_permiso, id_rol) values ('3', '3');
insert into rol_permiso (id_permiso, id_rol) values ('3', '4');
insert into rol_permiso (id_permiso, id_rol) values ('4', '1');
insert into rol_permiso (id_permiso, id_rol) values ('4', '2');
insert into rol_permiso (id_permiso, id_rol) values ('4', '3');
insert into rol_permiso (id_permiso, id_rol) values ('4', '4');
insert into rol_permiso (id_permiso, id_rol) values ('5', '1');
insert into rol_permiso (id_permiso, id_rol) values ('5', '2');
insert into rol_permiso (id_permiso, id_rol) values ('5', '3');
insert into rol_permiso (id_permiso, id_rol) values ('5', '4');
insert into rol_permiso (id_permiso, id_rol) values ('6', '1');
insert into rol_permiso (id_permiso, id_rol) values ('6', '2');
insert into rol_permiso (id_permiso, id_rol) values ('6', '3');
insert into rol_permiso (id_permiso, id_rol) values ('6', '4');
insert into rol_usuario (id_usuario, id_rol) values ('1', '1');
insert into rol_usuario (id_usuario, id_rol) values ('2', '2');
insert into rol_usuario (id_usuario, id_rol) values ('3', '3');
insert into rol_usuario (id_usuario, id_rol) values ('4', '4');
insert into rol_usuario (id_usuario, id_rol) values ('5', '1');
insert into rol_usuario (id_usuario, id_rol) values ('6', '3');
insert into rol_usuario (id_usuario, id_rol) values ('7', '2');
insert into rol_usuario (id_usuario, id_rol) values ('8', '4');
insert into rol_usuario (id_usuario, id_rol) values ('9', '3');
insert into rol_usuario (id_usuario, id_rol) values ('10', '1');
insert into rol_usuario (id_usuario, id_rol) values ('11', '2');
insert into rol_usuario (id_usuario, id_rol) values ('12', '4');
insert into rol_usuario (id_usuario, id_rol) values ('13', '4');
insert into rol_usuario (id_usuario, id_rol) values ('14', '1');
insert into rol_usuario (id_usuario, id_rol) values ('15', '3');